apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-service
  namespace: mumu
spec:
  type: ClusterIP  # 默认类型
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: nginx
